// Get Hot Manga Update
GET http://localhost:3000/api/manga/detail/raid/
###
GET http://localhost:3000/
###
GET http://localhost:3000/api/hot_manga_update/
### 
GET http://localhost:3000/api/manga/c-sword-and-cornett/
###
GET http://localhost:3000/api/manga/chapter/martial-peak-chapter-865-bahasa-indonesia/
###
GET http://localhost:3000/api/genre/all
###
GET http://localhost:3000/api/latest_update/1
###
GET http://localhost:3000/api/genre/action/5
###
GET http://localhost:3000/api/search/?query=dad
###
GET http://localhost:3000/api/manga/3
###
GET http://localhost:3000/api/manhwa/2
###
GET http://localhost:3000/api/manhua/4
###
GET http://localhost:3000/api/best_series
###