// Get Hot Manga Update
GET http://localhost:3000/api/manga/detail/ajin/
###
GET http://localhost:3000/
###
GET http://localhost:3000/api/hot_manga_update/
###
GET http://localhost:3000/api/manga/detail/mission-yozakura-family/
###
GET http://localhost:3000/api/manga/chapter/mission-yozakura-family-chapter-55-bahasa-indonesia/
###
GET http://localhost:3000/api/genre/all
###
GET http://localhost:3000/api/latest_update/2
###
GET http://localhost:3000/api/genre/action/5
###
GET http://localhost:3000/api/search/?query=dad
###
GET http://localhost:3000/api/manga/7
###
GET http://localhost:3000/api/manhwa/1
###
GET http://localhost:3000/api/manhua/3
###
GET http://localhost:3000/api/best_series
###